// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjwShzF5scHL5W0UmSVxuwd_Y_7KfjDTc',
    appId: '1:497360731607:web:0e006802b776f60741df92',
    messagingSenderId: '497360731607',
    projectId: 'sima-d3674',
    authDomain: 'sima-d3674.firebaseapp.com',
    storageBucket: 'sima-d3674.appspot.com',
    measurementId: 'G-KB3HV7NEF6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjjporrhWduwbWw15J1VqTINFLcX6m0CU',
    appId: '1:497360731607:android:b37f12f3914553ff41df92',
    messagingSenderId: '497360731607',
    projectId: 'sima-d3674',
    storageBucket: 'sima-d3674.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDduescMoLnRKL_lAVYBkLmfbCPIqeKP-Q',
    appId: '1:497360731607:ios:08892262214148d341df92',
    messagingSenderId: '497360731607',
    projectId: 'sima-d3674',
    storageBucket: 'sima-d3674.appspot.com',
    iosBundleId: 'com.example.sima',
  );
}
